import SwiftUI

@main
struct MyApp: App {
    
    @StateObject private var dataController = DataController()
    
    var body: some Scene {
        WindowGroup {
            ContentView().environment(\.managedObjectContext, dataController.container.viewContext).onAppear(){
                if(!UserDefaults.standard.bool(forKey: "firstUse")){
                    addAllLegends()
                    UserDefaults.standard.set(true,forKey: "firstUse")
                }
            }
        }
    }
    
    func addAllLegends(){
        DataController().addLegend(aName: "The hell house in New Orleans", aLocation: "New Orleans, Louisiana, United State of America", aLegenDescription: "Rue Royale in New Orleans boasts number 1140, an ornate building hiding a dark past. The LaLauries purchased the house in 1832, hosting opulent parties for local high society until rumors surfaced of abuse towards their slaves. In 1833 a neighbor witnessed Mrs. LaLaurie whipping a young slave girl who ran to her death rather than be caught. Mrs. LaLaurie was charged with abuse, but the slaves were returned to her family. Slaves continued to disappear, and a horrified cook started a fire to draw attention to the basement where the missing slaves were found. The room was filled with mutilated, tortured, and slaughtered slaves, turning public sentiment against the LaLauries. Mrs. LaLaurie fled, and the house was burned until its restoration in 1837. The new owners fled after a month, and many reported hearing heartbreaking screams and apparitions. During renovations, human remains were discovered, and the house was converted into luxury apartments. Its current owners have yet to notice anything strange.", aTag: "Ghosts,Mystery,Hell,Haunted House,Slaves,Slave,USA,United State of America,Real Fact", aImage: "theHellHouseInNewOrleans", aContext: dataController.container.viewContext)
        DataController().addLegend(aName: "Ghosts of the White House", aLocation: "Washington, District of Columbia, United State of America", aLegenDescription: "The White House is known for being haunted, with several ghostly tenants that have been reported over the years. The most distinguishable spirit is that of Abraham Lincoln. After his death, members of the presidential staff often heard his footsteps on the second floor, and he has been seen several times looking out of the Oval Office window. Some say that Nixon even followed Lincoln's advice given through his ghostly presence. Another haunted figure is Abigail Adams, the former first lady and wife of John Adams, the first to reside in the White House. She can still be seen today gliding through the East Wing with her arms full of see-through linen. Other spirits include former President Andrew Jackson, who is said to still sleep in the Pink Room and can be heard laughing, and the ghost of David Burns, who granted the land on which the White House was built. The grounds around the building are also haunted by the spirit of Dolley Madison, who appears to gardeners and orders them to leave her beautiful roses untouched, which have bloomed exactly as she wished for the past 200 years.", aTag: "Ghosts,Mystery,USA,United State of America,Real Fact,Washington,D.C.,DC,D.C,DC.,District of Columbia,White House,Haunted House", aImage: "ghostsOfTheWhiteHouse", aContext: dataController.container.viewContext)
        DataController().addLegend(aName: "The spirits of the battle of Chickamauga", aLocation: "Georgia, United State of America", aLegenDescription: "The Battle of Chickamauga in 1863 was a violent clash that took the lives of many soldiers on both sides. According to local legend, their spirits still roam the battlefield, trapped in an eternal struggle. Some believe these ghosts appear as ghostly figures or emit mournful cries, while others claim they are still fighting the battle. Of all the spirits, the most frightening is the Gray Man, a tall, thin figure draped in a gray uniform. Many say he is a Confederate soldier, while others believe he was a Union spy caught and executed by the Confederates. His face is said to be hidden by a wide-brimmed hat, and his eyes glow red in the darkness. Despite their fearsome reputation, some believe these spirits are not evil but simply lost and confused. Treating them with respect may earn their guidance or protection. However, the ghosts remain a haunting reminder of the toll of war and its impact on those who fight it.", aTag: "Ghosts,USA,United State of America,Real Fact,Battle,Georgia", aImage: "theSpiritsOfTheBattleOfChickamauga", aContext: dataController.container.viewContext)
        DataController().addLegend(aName: "The cursed hotel", aLocation: "Banff, Canada", aLegenDescription: "The Banff hotel is a grand building situated in the Canadian mountains, but it carries with it a dark legend that dates back to the First Nations people. They believed that the land was sacred and cursed the site where the hotel now stands. It's rumored that the malevolent spirits of those who perished on the land roam the hotel's halls, seeking revenge against those who have desecrated their resting place. Over the years, guests at the hotel have reported strange happenings, including apparitions, eerie noises, and physical attacks by unseen forces. The hotel's legend has grown more sinister over time, with stories of mysterious disappearances and unexplained deaths. Many believe that the Banff hotel is a portal to the spirit world or even hell itself. Despite the warnings and the hotel's dark reputation, it remains a popular destination for thrill-seekers and tourists drawn to its mystery and intrigue. The cursed hotel holds many secrets and dangers, and those who venture within its walls do so at their own risk. The malevolent spirits are relentless in their pursuit of revenge, and guests who stay too long are said to lose their grip on reality. Despite the risks, visitors to the hotel continue to come seeking adventure or driven by morbid curiosity. The Banff hotel is a monument to the power of legend and the human fascination with the unknown, drawing in those who are brave enough to face the curse that surrounds it.", aTag: "Ghosts,Real Fact,Hotel,Banff,Legend,Canada,Cursed,Spirit", aImage: "theCursedHotel", aContext: dataController.container.viewContext)
        DataController().addLegend(aName: "La Llorona", aLocation: "Messico", aLegenDescription: "La Llorona, also known as the weeping woman, is a popular legend that has been passed down through generations in Mexican and Latin American folklore. The tale of La Llorona tells of a beautiful woman named Maria who marries a wealthy nobleman and has two children with him. However, the nobleman soon neglects Maria, causing her to neglect her children as well. In a moment of madness, Maria drowns her children in a nearby river, consumed by grief and despair. She is then said to have disappeared, and her cries for her lost children can be heard throughout the village. The villagers believe that she still wanders the earth, trying to lure children to their deaths in an attempt to replace her own. The story of La Llorona serves as a warning to parents to be vigilant and attentive to their children's safety, particularly near water. It is a cautionary tale of the consequences of neglect and the dangers of the unchecked grief and despair that can overtake a person's mind and actions.", aTag: "Children,Ghost,Mexico,Woman,Tale,Nobleman", aImage: "Llorona", aContext: dataController.container.viewContext)
        DataController().addLegend(aName: "Rose Hall", aLocation: "Montengo Bay, Jamaica", aLegenDescription: "Rose Hall is a historic Georgian mansion located in Montego Bay, Jamaica. It was built in the 1770s by John Palmer, a wealthy Englishman who owned a large sugar plantation in Jamaica. The mansion is known for its impressive architecture and its association with the infamous legend of Annie Palmer, the White Witch of Rose Hall. According to legend, Annie Palmer was a cruel slave owner who was known for her ruthless treatment of her slaves and her numerous affairs. She was said to practice voodoo and black magic and was believed to have killed her three husbands and several other slaves. Her reign of terror was eventually brought to an end when a group of slaves revolted and killed her. The legend of Annie Palmer has fascinated visitors to Rose Hall for generations and has led to the mansion being dubbed \"the most haunted house in Jamaica.\" In recent years, the mansion has been restored and turned into a museum, allowing visitors to explore its rich history and learn more about the legend of Annie Palmer. Today, Rose Hall is a popular tourist destination in Montego Bay and attracts visitors from all over the world. Its stunning architecture and lush gardens make it a beautiful and picturesque location, while the legend of Annie Palmer adds a touch of mystery and intrigue. Whether you believe in the legend or not, a visit to Rose Hall is a fascinating and unforgettable experience.", aTag: "Witch,Jamaica,Legend,Slaves,Slave,Englishman", aImage: "roseHall", aContext: dataController.container.viewContext)
        DataController().addLegend(aName: "The Tower of London", aLocation: "London, England", aLegenDescription: "The Tower of London is a place of historical significance and legends. As a fortress built in the 11th century, it served as a royal palace, prison, and even a zoo. The Tower has witnessed many important events in British history, and it has become the subject of numerous legends. One of the most famous legends is about the Tower's ravens. It is said that if the six resident ravens ever leave, the Tower will fall and bring disaster to the kingdom. To prevent this from happening, the ravens have their wings clipped. This legend dates back to the 17th century and the ravens remain an integral part of the Tower's history and identity. The Tower's walls are also said to be haunted by ghostly apparitions. Anne Boleyn, King Henry VIII's second wife, was beheaded at the Tower in 1536, and her ghost is said to still wander the corridors carrying her severed head. The two princes, Edward V and Richard of York, who were famously murdered in the Tower in 1483, are also said to haunt its walls. Many notable events in British history have also occurred at the Tower, giving rise to legends. The attempted escape of the Countess of Nithsdale in 1716 is one such event. Her husband had been imprisoned in the Tower for his involvement in the Jacobite rising, and the Countess disguised herself as a washerwoman to gain access to his cell. She managed to smuggle him out of the Tower in a laundry basket, and the legend of her daring escape lives on. In conclusion, the Tower of London is a mysterious and fascinating place, with legends that add to its allure. The ravens that protect it, the ghostly apparitions that haunt it, and the daring escapes that have taken place within its walls are all a part of the Tower's rich history. Whether these legends are true or not, they have become a vital part of the Tower's identity and will continue to fascinate visitors for years to come.", aTag: "Ghost,London,England,Tower,Legend", aImage: "theTowerOfLondon", aContext: dataController.container.viewContext)
        DataController().addLegend(aName: "Blody Mary", aLocation: "England", aLegenDescription: "Bloody Mary is a legendary ghost or spirit that can be conjured to reveal the future. The ritual is usually performed in a group setting, with participants chanting her name repeatedly in front of a mirror. The appearance of Bloody Mary can be either benign or malevolent, depending on the variation of the legend. The original divination ritual involved young women walking up a flight of stairs backward, holding a candle and a hand mirror, to catch a glimpse of their future husband's face. However, there was a chance that they would see a skull instead, indicating an untimely death. In the modern ritual, Bloody Mary allegedly appears to individuals or groups who invoke her name into a dimly-lit or candle-lit mirror, with the possibility of encountering a friendly or evil apparition, often covered in blood. The lore surrounding the ritual states that participants may endure terrifying encounters such as screaming, cursing, strangling, stealing of souls, blood drinking, or eye scratching. The legend of Hanako-san in Japan is similar to the Bloody Mary mythology.", aTag: "Ghost,England,Legend,Ritual,Mirror,Blood,Urban Legend", aImage: "blodyMary", aContext: dataController.container.viewContext)
        DataController().addLegend(aName: "Hanako-san", aLocation: "Japan", aLegenDescription: "Hanako-san, or Toire no Hanako-san, is a Japanese urban legend about the ghost of a young girl who haunts school toilets. The origins of the legend vary, with different versions stating that she was killed during World War II, murdered by a parent or stranger, or committed suicide due to bullying. To summon Hanako-san, individuals must enter a girls' toilet, knock three times on the third stall, and ask if she is present. If she is there, she will reply with some variation of \"Yes, I am.\" The legend has achieved popularity in Japanese schools, and Hanako-san has been depicted in various media, including films, manga, anime, and video games. The character is not always portrayed as female, and some depictions show a male version called Hanako-kun. The legend of Hanako-san dates back to the 1950s, but has become part of popular culture in Japan, and NPR described her as having \"become a fixture of Japanese urban folklore over the last 70 years.\"", aTag: "Ghost,Japan,Legend,Urban Legend,Toilette", aImage: "Hanako-san", aContext: dataController.container.viewContext)
        DataController().addLegend(aName: "Krampus", aLocation: "Germany, Europe", aLegenDescription: "Krampus is a legendary figure from Alpine folklore who punishes misbehaving children during the Christmas season. He is often depicted as a demonic figure with horns, hooves, and sharp fangs, carrying a bundle of birch branches or a whip. The Krampus tradition is believed to have originated in pre-Christian pagan customs and evolved to incorporate Christian themes. The Krampus is a contrast to St. Nicholas, who rewards good behavior, and serves as a reminder to children of the importance of good behavior and the consequences of misbehavior. The Krampus has gained renewed popularity in recent years through Krampus-themed festivals and parades. Despite its frightening appearance, the legend of the Krampus remains a fascinating figure that continues to captivate the imagination of people around the world.", aTag: "Legend,Urban Legend,Europe,Germany,Christmas", aImage: "Krampus", aContext: dataController.container.viewContext)
    }
    
}
